//package com.kelompok5.kantin.helper;
//
//import android.content.Context;
//import android.database.Cursor;
//import android.database.sqlite.SQLiteDatabase;
//import android.database.sqlite.SQLiteOpenHelper;
//import android.util.Log;
//
//public class SqliteHelper extends SQLiteOpenHelper {
//
//    private static final String DATABASE_NAME ="kantin.db";
//    private static final int DATABASE_VERSION =1;
//    public SqliteHelper(Context context) {
//        super(context, DATABASE_NAME, null, DATABASE_VERSION);
//        //todo autogenerated constructor stub
//    }
//
//    @Override
//    public void onCreate(SQLiteDatabase db) {
//        //todo autogenerated constructor stub
//        String[] sql= {
//                    "Create table tb_driver(id_driver INTERGER PRIMARY KEY, nama_driver text null, alamat text null, usernmae text null, password text null, email text null, no_telephone text null);",
//                    //"CREATE TABLE IF NOT EXISTS tb_ayam(nim_send text primary key);"
//                    };
//
//        Log.d( "data", "onCreate:" + sql);
//        for(String sqla : sql){
//            db.execSQL(sqla);
//        }
//    }
//
//    @Override
//    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
//
//    }
//
//    public boolean Authenticate(Login login) {
//        try{
//            SQLiteDatabase db = this.getReadableDatabase();
//            Cursor cursor = db.query("tb_driver",// Selecting Table
//                    new String[]{"username", "password"},//Selecting columns want to query
//                    "username" + "=?",
//                    new String[]{login.nim},//Where clause
//                    null, null, null);
//            if(cursor.moveToFirst() && cursor.getCount() > 0 && cursor != null){
//                if(cursor.getString(cursor.getColumnIndex("password")).equals(login.password)){
//                    return true;
//                }else{
//                    return false;
//                }
//            }else{
//                return false;
//            }
//        }catch(Exception e){
//            Log.d("Auth Ex : ", e.getMessage());
//            return false;
//        }
//
//
//    }
//}