package com.kelompok5.kantin.helper;

import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import com.kelompok5.kantin.activity.login.Login;

public class SqliteHelper extends SQLiteOpenHelper {

    private static final String DATABASE_NAME ="kantin.db";
    private static final int DATABASE_VERSION =1;
    public SqliteHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
        //todo autogenerated constructor stub
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        //todo autogenerated constructor stub
        String sql= "Create table tb_usersend(nim_send text primary key, nama_lengkap text null, telepon text null, kata_sandi text null);";
        Log.d( "data", "onCreate:" + sql);
        db.execSQL(sql);
        // sql = "INSERT INTO tb_usersend (nim_send,nama_lengkap, telepon, kata_sandi) VALUES('E41180449','Refandra','03317812289','1');";
       // db.execSQL(sql);

    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }

    public boolean Authenticate(Login login) {
        try{
            SQLiteDatabase db = this.getReadableDatabase();
            Cursor cursor = db.query("tb_usersend",// Selecting Table
                    new String[]{"nim_send", "kata_sandi"},//Selecting columns want to query
                    "nim_send" + "=?",
                    new String[]{login.nim},//Where clause
                    null, null, null);
            if(cursor.moveToFirst() && cursor.getCount() > 0 && cursor != null){
                if(cursor.getString(cursor.getColumnIndex("kata_sandi")).equals(login.password)){
                    return true;
                }else{
                    return false;
                }
            }else{
                return false;
            }
        }catch(Exception e){
            Log.d("Auth Ex : ", e.getMessage());
            return false;
        }


    }
}